version: 1.3.0
jobs:
  test:
    macos:
      xcode: "10.2.1"
    branch: master
    steps:
      - run:
          name: UI and Unit Test
	  command: fastlane test
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps: 
      - run: echo 'Hello world!'

