version: 2
jobs:
  test:
    macos:
      xcode: "10.2.1"
    steps:
      - checkout
      - run: fastlane test
  deploy:
    macos:
      xcode: "10.2.1"
    steps:
      - checkout
      - deploy:
          name: Deploy
          command: fastlane deploy

workflows:
  version: 2
  test_release:
    jobs:
      - test
      - deploy:
          requires:
            test
          filters:
            branches:
              only: release

